// Copyright (c) Mahmoud Shaheen. All rights reserved.

namespace Headless.Api.Models;

/// <summary>
/// Base problem details schema used for OpenAPI response documentation across all Headless error responses.
/// Extends the RFC 7807 / RFC 9457 Problem Details contract with Headless-specific observability fields.
/// </summary>
public class HeadlessProblemDetails
{
    /// <summary>A URI reference that identifies the problem type (RFC 7807 <c>type</c>).</summary>
    public required string Type { get; init; }

    /// <summary>A short, human-readable summary of the problem type (RFC 7807 <c>title</c>).</summary>
    public required string Title { get; init; }

    /// <summary>The HTTP status code generated by the origin server (RFC 7807 <c>status</c>).</summary>
    public required int Status { get; init; }

    /// <summary>A human-readable explanation specific to this occurrence (RFC 7807 <c>detail</c>).</summary>
    public required string Detail { get; init; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem, typically the request path
    /// (RFC 7807 <c>instance</c>).
    /// </summary>
    public required string Instance { get; init; }

    /// <summary>The distributed trace identifier for correlating this error across services.</summary>
    public required string TraceId { get; init; }

    /// <summary>The application build version at the time the error occurred.</summary>
    public required string BuildNumber { get; init; }

    /// <summary>The source-control commit hash at the time the error occurred.</summary>
    public required string CommitNumber { get; init; }

    /// <summary>The UTC timestamp at which the error response was produced.</summary>
    public required DateTimeOffset Timestamp { get; init; }
}
