<Project Sdk="Headless.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tests</RootNamespace>
    <IsTestProject>false</IsTestProject>
    <IsTestHarnessProject>true</IsTestHarnessProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Headless.Hosting\Headless.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Headless.Idempotency\Headless.Idempotency.csproj" />
    <ProjectReference Include="..\..\src\Headless.Idempotency.InMemory\Headless.Idempotency.InMemory.csproj" />
    <ProjectReference Include="..\..\src\Headless.Testing\Headless.Testing.csproj" />
    <ProjectReference Include="..\..\src\Headless.Testing.Testcontainers\Headless.Testing.Testcontainers.csproj" />
  </ItemGroup>
</Project>
