<Project Sdk="Headless.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>MVC integration for Headless API.</Description>
    <PackageTags>headless;api;mvc;dotnet</PackageTags>
    <RootNamespace>Headless.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Headless.Api.Mvc.Tests.Unit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Headless.Api\Headless.Api.csproj" />
  </ItemGroup>
</Project>
