//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Settings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Settings.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting definition not found for setting name: {0}..
        /// </summary>
        internal static string setting_not_defined {
            get {
                return ResourceManager.GetString("setting:not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting provider is readonly for provider key: {0} and can&apos;t be modified..
        /// </summary>
        internal static string setting_provider_is_readonly {
            get {
                return ResourceManager.GetString("setting:provider_is_readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting provider not found for provider name: {0}..
        /// </summary>
        internal static string setting_provider_not_found {
            get {
                return ResourceManager.GetString("setting:provider_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant is not available to use with setting provider..
        /// </summary>
        internal static string setting_tenant_not_available {
            get {
                return ResourceManager.GetString("setting:tenant_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not available to use with setting provider..
        /// </summary>
        internal static string setting_user_not_available {
            get {
                return ResourceManager.GetString("setting:user_not_available", resourceCulture);
            }
        }
    }
}
