<Project>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <EmitCompilerGeneratedFiles>false</EmitCompilerGeneratedFiles>
    <GenerateSBOM Condition="'$(GenerateSBOM)' == ''">true</GenerateSBOM>
  </PropertyGroup>
  <ItemGroup Label="Package References">
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
    <Using Include="JetBrains.Annotations" />
  </ItemGroup>
  <ItemGroup Label="Analyzer configuration">
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)eng/analyzers/*.txt" />
  </ItemGroup>
</Project>
