<Project Sdk="Headless.NET.Sdk.Test">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tests</RootNamespace>
    <IsTestProject>false</IsTestProject>
    <IsTestHarnessProject>true</IsTestHarnessProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Humanizer.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Headless.DistributedLocks\Headless.DistributedLocks.csproj" />
    <ProjectReference Include="..\..\src\Headless.Testing\Headless.Testing.csproj" />
  </ItemGroup>
</Project>
