//HintName: LongPrimitiveDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using Framework.Primitives;
using Framework.Generator.Primitives;

namespace Framework.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "LongPrimitive"/></summary>
public sealed class LongPrimitiveDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<LongPrimitive>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, LongPrimitive value)
    {
        parameter.Value = value.GetUnderlyingPrimitiveType();
    }

    public override LongPrimitive Parse(object value)
    {
        return value switch
        {
            byte byteValue => new LongPrimitive(byteValue)
            long longValue => new LongPrimitive(longValue)
            int intValue => new LongPrimitive(intValue)
            short shortValue => new LongPrimitive(shortValue)
            decimal decimalValue and < long.MaxValue and > long.MinValue => new LongPrimitive((long)decimalValue)
            string stringValue when !string.IsNullOrEmpty(stringValue) && long.TryParse(stringValue, c out var result) => new LongPrimitive(result)
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to LongPrimitive"),
        };
    }
}
