//HintName: AddSwashbuckleSwaggerPrimitivesMappingsExtensions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Framework.Primitives;
using Microsoft.Extensions.DependencyInjection;
using Swashbuckle.AspNetCore.SwaggerGen;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Any;
using Framework.Generator.Primitives;

[assembly: Framework.Generator.Primitives.PrimitiveAssemblyAttribute]
namespace generator_Test.Converters.Extensions;

/// <summary>Helper class providing methods to configure Swagger mappings for Primitive types of generator_Test</summary>
public static class AddSwashbuckleSwaggerPrimitivesMappingsExtensions
{
    /// <summary>Adds Swagger mappings for specific custom types to ensure proper OpenAPI documentation generation.</summary>
    /// <param name="options">The SwaggerGenOptions instance to which mappings are added.</param>
    /// <remarks>
    /// The method adds Swagger mappings for the following types:
    /// <see cref="TimeSpanPrimitive" />
    /// </remarks>
    public static void AddSwaggerPrimitiveMappings(this SwaggerGenOptions options)
    {
        options.MapType<TimeSpanPrimitive>(() => new OpenApiSchema
        {
            Type = "integer",
            Format = "int64",
            Title = "TimeSpanPrimitive"
        });
        options.MapType<TimeSpanPrimitive?>(() => new OpenApiSchema
        {
            Type = "integer",
            Format = "int64",
            Nullable = true,
            Title = "Nullable<TimeSpanPrimitive>"
        });
    }
}
