// Copyright (c) Mahmoud Shaheen. All rights reserved.

using Headless.Api.Filters;
using Headless.Checks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Headless.Api.Middlewares;

/// <summary>
/// To improve Search Engine Optimization SEO, there should only be a single URL for each resource. Case
/// differences and/or URL's with/without trailing slashes are treated as different URL's by search engines. This
/// rewrite rule redirects all non-canonical URL's based on the settings specified to their canonical equivalent.
/// Note: Non-canonical URL's are not generated by this site template, it is usually external sites which are
/// linking to your site but have changed the URL case or added/removed trailing slashes.
/// (See Google's comments at http://googlewebmastercentral.blogspot.co.uk/2010/04/to-slash-or-not-to-slash.html
/// and Bing's at http://blogs.bing.com/webmaster/2012/01/26/moving-content-think-301-not-relcanonical).
/// </summary>
/// <remarks>
/// <para>
/// <b>Ordering requirement</b> — register this rule AFTER <c>UseRouting()</c>, ideally through
/// <see cref="Headless.Api.SetupCanonicalUrl.UseRedirectToCanonicalUrl(Microsoft.AspNetCore.Builder.IApplicationBuilder)"/>.
/// The <see cref="Headless.Api.Filters.NoTrailingSlashAttribute"/> and
/// <see cref="Headless.Api.Filters.NoLowercaseQueryStringAttribute"/> opt-outs are read from endpoint metadata,
/// which only exists once <c>EndpointRoutingMiddleware</c> has matched the request.
/// </para>
/// <para>
/// Requests with no routed endpoint — either because the rule runs before routing, or because nothing matched —
/// are left untouched: the rule cannot tell whether such a request opted out, and redirecting anyway would
/// corrupt values the endpoint asked to preserve (for example a case-sensitive OAuth <c>state</c> parameter).
/// A one-time warning is logged the first time this happens so a misordered pipeline is visible in the logs.
/// </para>
/// </remarks>
[PublicAPI]
public sealed partial class RedirectToCanonicalUrlRule : IRule
{
    private const char _SlashCharacter = '/';

    // Fires at most once per rule instance (one registration = one pipeline position) to avoid log spam on
    // every unmatched request. 0 = not yet warned, 1 = warned.
    private int _endpointUnavailableWarningEmitted;

    /// <summary>
    /// Initializes the rule, reading <see cref="AppendTrailingSlash"/> and <see cref="LowercaseUrls"/>
    /// from <c>RouteOptions</c>.
    /// </summary>
    /// <param name="optionsAccessor">The route options accessor.</param>
    /// <exception cref="ArgumentNullException"><paramref name="optionsAccessor"/> is <see langword="null"/>.</exception>
    public RedirectToCanonicalUrlRule(IOptions<RouteOptions> optionsAccessor)
    {
        Argument.IsNotNull(optionsAccessor);
        AppendTrailingSlash = optionsAccessor.Value.AppendTrailingSlash;
        LowercaseUrls = optionsAccessor.Value.LowercaseUrls;
    }

    /// <summary>
    /// Initializes the rule with explicit trailing-slash and lowercase settings.
    /// </summary>
    /// <param name="appendTrailingSlash">When <see langword="true"/>, a trailing slash is appended; when <see langword="false"/>, it is stripped.</param>
    /// <param name="lowercaseUrls">When <see langword="true"/>, the path and query string are lower-cased (query only when no <see cref="Headless.Api.Filters.NoLowercaseQueryStringAttribute"/> is present).</param>
    public RedirectToCanonicalUrlRule(bool appendTrailingSlash, bool lowercaseUrls)
    {
        AppendTrailingSlash = appendTrailingSlash;
        LowercaseUrls = lowercaseUrls;
    }

    /// <summary>
    /// Gets a value indicating whether to append trailing slashes.
    /// </summary>
    /// <value>
    /// <see langword="true"/> if appending trailing slashes; otherwise, strip trailing slashes.
    /// </value>
    public bool AppendTrailingSlash { get; }

    /// <summary>
    /// Gets a value indicating whether to lower-case all URL's.
    /// </summary>
    /// <value>
    /// <see langword="true"/> if lower-casing URL's; otherwise, <see langword="false"/>.
    /// </value>
    public bool LowercaseUrls { get; }

    /// <summary>
    /// Evaluates the current GET request and issues a 301 Permanent Redirect when the URL is not
    /// canonical (wrong trailing-slash presence or mixed-case path/query). Non-GET requests are
    /// passed through unchanged.
    /// </summary>
    /// <param name="context">The rewrite context for the current request.</param>
    /// <exception cref="ArgumentNullException"><paramref name="context"/> is <see langword="null"/>.</exception>
    public void ApplyRule(RewriteContext context)
    {
        Argument.IsNotNull(context);

        if (HttpMethods.IsGet(context.HttpContext.Request.Method))
        {
            if (!_TryGetCanonicalUrl(context, out var canonicalUrl))
            {
                _HandleNonCanonicalRequest(context, canonicalUrl);
            }
        }
    }

    /// <summary>
    /// Determines whether the specified URl is canonical and if it is not, outputs the canonical URL.
    /// </summary>
    /// <param name="context">The <see cref="RewriteContext" />.</param>
    /// <param name="canonicalUrl">The canonical URL.</param>
    /// <returns><see langword="true"/> if the URL is canonical, otherwise <see langword="false"/>.</returns>
    private bool _TryGetCanonicalUrl(RewriteContext context, [NotNullWhen(false)] out Uri? canonicalUrl)
    {
        Argument.IsNotNull(context);

        var endpoint = context.HttpContext.GetEndpoint();

        // Every canonicalization below is opt-out-able through endpoint metadata, which is populated by
        // EndpointRoutingMiddleware. Without a routed endpoint the opt-outs are invisible rather than absent,
        // so treating the URL as canonical is the only answer that cannot violate them.
        if (endpoint is null)
        {
            _WarnEndpointUnavailable(context);
            canonicalUrl = null;

            return true;
        }

        // Cache attribute lookups to avoid O(n) metadata scans on each check
        var hasNoTrailingSlash = endpoint.Metadata.GetMetadata<NoTrailingSlashAttribute>() is not null;
        var hasNoLowercaseQueryString = endpoint.Metadata.GetMetadata<NoLowercaseQueryStringAttribute>() is not null;

        var isCanonical = true;

        var request = context.HttpContext.Request;
        var hasPath = request.Path.HasValue && request.Path.Value.Length > 1;

        // If we are not dealing with the home page. Note, the home page is a special case and it doesn't matter
        // if there is a trailing slash or not. Both will be treated as the same by search engines.
        if (hasPath)
        {
            var hasTrailingSlash = request.Path.Value![^1] == _SlashCharacter;

            if (AppendTrailingSlash)
            {
                // Append a trailing slash to the end of the URL.
                if (!hasTrailingSlash && !hasNoTrailingSlash)
                {
                    request.Path = new PathString(request.Path.Value + _SlashCharacter);
                    isCanonical = false;
                }
            }
            else
            {
                // Trim a trailing slash from the end of the URL.
                if (hasTrailingSlash)
                {
                    request.Path = new PathString(request.Path.Value.TrimEnd(_SlashCharacter));
                    isCanonical = false;
                }
            }
        }

        if (hasPath || request.QueryString.HasValue)
        {
            // Lowercasing must NOT be gated on the NoTrailingSlash opt-out — that attribute only
            // suppresses trailing-slash normalization. The query has its own NoLowercaseQueryString
            // opt-out below; path lowercasing has no opt-out attribute.
            if (LowercaseUrls)
            {
                if (hasPath)
                {
                    foreach (var character in request.Path.Value!)
                    {
                        if (char.IsUpper(character))
                        {
                            request.Path = new PathString(request.Path.Value.ToLowerInvariant());
                            isCanonical = false;

                            break;
                        }
                    }
                }

                if (request.QueryString.HasValue && !hasNoLowercaseQueryString)
                {
                    foreach (var character in request.QueryString.Value!)
                    {
                        if (char.IsUpper(character))
                        {
                            request.QueryString = new QueryString(request.QueryString.Value.ToLowerInvariant());
                            isCanonical = false;

                            break;
                        }
                    }
                }
            }
        }

        canonicalUrl = isCanonical ? null : new Uri(request.GetEncodedUrl(), UriKind.Absolute);

        return isCanonical;
    }

    /// <summary>
    /// Handles HTTP requests for URL's that are not canonical. Performs a 301 Permanent Redirect to the canonical URL.
    /// </summary>
    /// <param name="context">The <see cref="RewriteContext" />.</param>
    /// <param name="canonicalUrl">The canonical URL.</param>
    private static void _HandleNonCanonicalRequest(RewriteContext context, Uri canonicalUrl)
    {
        Argument.IsNotNull(context);
        Argument.IsNotNull(canonicalUrl);

        var response = context.HttpContext.Response;
        response.StatusCode = StatusCodes.Status301MovedPermanently;
        context.Result = RuleResult.EndResponse;
        response.Headers.Location = canonicalUrl.ToString();
    }

    /// <summary>
    /// Logs, at most once per rule instance, that canonicalization was skipped because the request carried no
    /// routed endpoint — the signal that the rule is registered before <c>UseRouting()</c>.
    /// </summary>
    /// <param name="context">The <see cref="RewriteContext" />.</param>
    private void _WarnEndpointUnavailable(RewriteContext context)
    {
        // Only RewriteMiddleware populates RewriteContext.Logger, so it is absent when the rule is driven
        // directly (tests, custom hosts) despite the non-nullable annotation.
        ILogger? logger = context.Logger;

        if (logger is null || Volatile.Read(ref _endpointUnavailableWarningEmitted) != 0)
        {
            return;
        }

        if (Interlocked.CompareExchange(ref _endpointUnavailableWarningEmitted, 1, 0) != 0)
        {
            return;
        }

        LogEndpointUnavailableWarning(logger);
    }

    [LoggerMessage(
        EventId = 0,
        EventName = "HEADLESS_CANONICAL_URL_ENDPOINT_UNAVAILABLE",
        Level = LogLevel.Warning,
        Message = "RedirectToCanonicalUrlRule skipped URL canonicalization because the request has no routed "
            + "endpoint. Requests matching no endpoint are never canonicalized; if canonical redirects are "
            + "expected here, register the rule AFTER UseRouting() (app.UseRouting(); "
            + "app.UseRedirectToCanonicalUrl();) so [NoTrailingSlash] and [NoLowercaseQueryString] endpoint "
            + "metadata is visible. This warning is emitted once per rule instance."
    )]
    // ReSharper disable once InconsistentNaming
    private static partial void LogEndpointUnavailableWarning(ILogger logger);
}
