<Project Sdk="Headless.NET.Sdk.Test">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tests</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Headless.Coordination.Sqlite\Headless.Coordination.Sqlite.csproj" />
    <ProjectReference Include="..\Headless.Coordination.Tests.Harness\Headless.Coordination.Tests.Harness.csproj" />
    <ProjectReference Include="..\Headless.Sql.Tests.Harness\Headless.Sql.Tests.Harness.csproj" />
  </ItemGroup>
</Project>
