//HintName: BytePrimitiveJsonConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Headless.Permissions;
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;
using System.Text.Json.Serialization.Metadata;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>JsonConverter for <see cref = "BytePrimitive"/></summary>
public sealed class BytePrimitiveJsonConverter : JsonConverter<BytePrimitive>
{
    /// <inheritdoc/>
    public override BytePrimitive Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        try
        {
            return JsonInternalConverters.ByteConverter.Read(ref reader, typeToConvert, options);
        }
        catch (InvalidPrimitiveValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void Write(Utf8JsonWriter writer, BytePrimitive value, JsonSerializerOptions options)
    {
        JsonInternalConverters.ByteConverter.Write(writer, (byte)value, options);
    }

    /// <inheritdoc/>
    public override BytePrimitive ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        try
        {
            return JsonInternalConverters.ByteConverter.ReadAsPropertyName(ref reader, typeToConvert, options);
        }
        catch (InvalidPrimitiveValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void WriteAsPropertyName(Utf8JsonWriter writer, BytePrimitive value, JsonSerializerOptions options)
    {
        JsonInternalConverters.ByteConverter.WriteAsPropertyName(writer, (byte)value, options);
    }
}
