//HintName: AddSwashbuckleSwaggerPrimitivesMappingsExtensions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Headless.Primitives;
using Microsoft.Extensions.DependencyInjection;
using Swashbuckle.AspNetCore.SwaggerGen;
using Headless.Generator.Primitives;

[assembly: Headless.Generator.Primitives.PrimitiveAssemblyAttribute]
namespace generator_Test.Converters.Extensions;

/// <summary>Helper class providing methods to configure Swagger mappings for Primitive types of generator_Test</summary>
public static class AddSwashbuckleSwaggerPrimitivesMappingsExtensions
{
    /// <summary>Adds Swagger mappings for specific custom types to ensure proper OpenAPI documentation generation.</summary>
    /// <param name="options">The SwaggerGenOptions instance to which mappings are added.</param>
    /// <remarks>
    /// The method adds Swagger mappings for the following types:
    /// <see cref="BoolPrimitive" />
    /// </remarks>
    public static void AddSwaggerPrimitiveMappings(this SwaggerGenOptions options)
    {
        options.MapType<BoolPrimitive>(() => new OpenApiSchema
        {
            Type = "boolean",
            Title = "BoolPrimitive"
        });
        options.MapType<BoolPrimitive?>(() => new OpenApiSchema
        {
            Type = "boolean",
            Nullable = true,
            Title = "Nullable<BoolPrimitive>"
        });
    }
}
