//HintName: CharPrimitiveDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using Headless.Permissions;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "CharPrimitive"/></summary>
public sealed class CharPrimitiveDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<CharPrimitive>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, CharPrimitive value)
    {
        parameter.Value = value.GetUnderlyingPrimitiveType();
    }

    public override CharPrimitive Parse(object value)
    {
        return value switch
        {
            char charValue => new CharPrimitive(charValue)
            string stringValue when !string.IsNullOrEmpty(stringValue) && char.TryParse(stringValue, out var charValue) => new CharPrimitive(charValue)
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to CharPrimitive"),
        };
    }
}
