//HintName: DoublePrimitiveDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using Headless.Permissions;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "DoublePrimitive"/></summary>
public sealed class DoublePrimitiveDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<DoublePrimitive>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, DoublePrimitive value)
    {
        parameter.Value = value.GetUnderlyingPrimitiveType();
    }

    public override DoublePrimitive Parse(object value)
    {
        return value switch
        {
            double doubleValue => new DoublePrimitive(doubleValue)
            float floatValue => new DoublePrimitive(floatValue)
            byte byteValue => new DoublePrimitive(byteValue)
            short shortValue => new DoublePrimitive(shortValue)
            long longValue => new DoublePrimitive(longValue)
            int intValue => new DoublePrimitive(intValue)
            string stringValue when !string.IsNullOrEmpty(stringValue) && double.TryParse(stringValue, global::System.Globalization.CultureInfo.InvariantCulture, out var result) => new DoublePrimitive(result)
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to DoublePrimitive"),
        };
    }
}
