//HintName: AddPrimitivesValueConvertersExtensions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Headless.Permissions;
using Headless.Primitives.Converters;
using Microsoft.EntityFrameworkCore;

namespace generator_Test.Converters.Extensions;

/// <summary>Helper class providing methods to configure Entity Framework Value Converters for Primitive types of generator_Test</summary>
public static class AddPrimitivesValueConvertersExtensions
{
    /// <summary>Adds Entity Framework Value Converters for specific custom types to ensure proper mapping to EF ORM.</summary>
    /// <param name="configurationBuilder">The ModelConfigurationBuilder instance to which converters are added.</param>
    public static global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder AddPrimitivePropertyConversions(this global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder.Properties<UShortPrimitive>().HaveConversion<UShortPrimitiveValueConverter>();
        return configurationBuilder;
    }
}
