//HintName: ShortPrimitiveDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using Headless.Permissions;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "ShortPrimitive"/></summary>
public sealed class ShortPrimitiveDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<ShortPrimitive>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, ShortPrimitive value)
    {
        parameter.Value = value.GetUnderlyingPrimitiveType();
    }

    public override ShortPrimitive Parse(object value)
    {
        return value switch
        {
            byte byteValue => new ShortPrimitive(byteValue)
            short shortValue => new ShortPrimitive(shortValue)
            int intValue and < short.MaxValue and > short.MinValue => new ShortPrimitive((short)intValue)
            long longValue and < short.MaxValue and > short.MinValue => new ShortPrimitive((short)longValue)
            decimal decimalValue and < short.MaxValue and > short.MinValue => new ShortPrimitive((short)decimalValue)
            string stringValue when !string.IsNullOrEmpty(stringValue) && short.TryParse(stringValue, global::System.Globalization.CultureInfo.InvariantCulture, out var result) => new ShortPrimitive(result)
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to ShortPrimitive"),
        };
    }
}
