//HintName: UShortPrimitiveDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using Headless.Permissions;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "UShortPrimitive"/></summary>
public sealed class UShortPrimitiveDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<UShortPrimitive>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, UShortPrimitive value)
    {
        parameter.Value = value.GetUnderlyingPrimitiveType();
    }

    public override UShortPrimitive Parse(object value)
    {
        return value switch
        {
            ushort primitiveValue => new UShortPrimitive(primitiveValue),
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to UShortPrimitive"),
        };
    }
}
