//HintName: DateTimePrimitiveDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using Headless.Primitives;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "DateTimePrimitive"/></summary>
public sealed class DateTimePrimitiveDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<DateTimePrimitive>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, DateTimePrimitive value)
    {
        parameter.Value = value.GetUnderlyingPrimitiveType();
    }

    public override DateTimePrimitive Parse(object value)
    {
        return value switch
        {
            global::System.DateTime dateOnly => new DateTimePrimitive(dateOnly)
            global::System.DateTimeOffset dateTimeOffset => new DateTimePrimitive(dateTimeOffset.DateTime)
            string stringValue when !string.IsNullOrEmpty(stringValue) && global::System.DateTime.TryParseExact(stringValue, "o", global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.AssumeLocal, out var result) => new DateTimePrimitive(result)
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to DateTimePrimitive"),
        };
    }
}
