//HintName: SBytePrimitiveTypeConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Headless.Permissions;
using System;
using System.ComponentModel;
using System.Globalization;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>TypeConverter for <see cref = "SBytePrimitive"/></summary>
public sealed class SBytePrimitiveTypeConverter : SByteConverter
{
    /// <inheritdoc/>
    public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
    {
        var result = base.ConvertFrom(context, culture, value);

        if (result is null)
        {
            return null;
        }

        try
        {
            return new SBytePrimitive((sbyte)result);
        }
        catch (InvalidPrimitiveValueException ex)
        {
            throw new FormatException("Cannot parse SBytePrimitive", ex);
        }
    }
}
