//HintName: BoolPrimitiveDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using Headless.Primitives;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "BoolPrimitive"/></summary>
public sealed class BoolPrimitiveDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<BoolPrimitive>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, BoolPrimitive value)
    {
        parameter.Value = value.GetUnderlyingPrimitiveType();
    }

    public override BoolPrimitive Parse(object value)
    {
        return value switch
        {
            bool boolValue => new BoolPrimitive(boolValue)
            string stringValue when !string.IsNullOrEmpty(stringValue) && bool.TryParse(stringValue, out var result) => new BoolPrimitive(result)
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to BoolPrimitive"),
        };
    }
}
