//HintName: StringOfStringPrimitiveValueConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Headless.Permissions;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Headless.Generator.Primitives;

namespace Headless.Primitives.EntityFrameworkCore.Converters;

/// <summary>ValueConverter for <see cref = "StringOfStringPrimitive"/></summary>
public sealed class StringOfStringPrimitiveValueConverter : ValueConverter<StringOfStringPrimitive, string>
{
    public StringOfStringPrimitiveValueConverter() : base(v => v, v => v) { }

    public StringOfStringPrimitiveValueConverter(ConverterMappingHints? mappingHints = null) : base(v => v, v => v, mappingHints) { }
}
