//HintName: TimeSpanPrimitiveDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using Headless.Primitives;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "TimeSpanPrimitive"/></summary>
public sealed class TimeSpanPrimitiveDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<TimeSpanPrimitive>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, TimeSpanPrimitive value)
    {
        parameter.Value = value.GetUnderlyingPrimitiveType();
    }

    public override TimeSpanPrimitive Parse(object value)
    {
        return value switch
        {
            global::System.TimeSpan timeSpan => new TimeSpanPrimitive(timeSpan)
            string stringValue when !string.IsNullOrEmpty(stringValue) && global::System.TimeSpan.TryParse(stringValue, global::System.Globalization.CultureInfo.InvariantCulture, out var result) => new TimeSpanPrimitive(result)
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to TimeSpanPrimitive"),
        };
    }
}
