//HintName: LongPrimitiveJsonConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Headless.Permissions;
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;
using System.Text.Json.Serialization.Metadata;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>JsonConverter for <see cref = "LongPrimitive"/></summary>
public sealed class LongPrimitiveJsonConverter : JsonConverter<LongPrimitive>
{
    /// <inheritdoc/>
    public override LongPrimitive Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        try
        {
            return JsonInternalConverters.Int64Converter.Read(ref reader, typeToConvert, options);
        }
        catch (InvalidPrimitiveValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void Write(Utf8JsonWriter writer, LongPrimitive value, JsonSerializerOptions options)
    {
        JsonInternalConverters.Int64Converter.Write(writer, (long)value, options);
    }

    /// <inheritdoc/>
    public override LongPrimitive ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        try
        {
            return JsonInternalConverters.Int64Converter.ReadAsPropertyName(ref reader, typeToConvert, options);
        }
        catch (InvalidPrimitiveValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void WriteAsPropertyName(Utf8JsonWriter writer, LongPrimitive value, JsonSerializerOptions options)
    {
        JsonInternalConverters.Int64Converter.WriteAsPropertyName(writer, (long)value, options);
    }
}
