//HintName: BoolPrimitiveJsonConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Headless.Primitives;
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;
using System.Text.Json.Serialization.Metadata;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>JsonConverter for <see cref = "BoolPrimitive"/></summary>
public sealed class BoolPrimitiveJsonConverter : JsonConverter<BoolPrimitive>
{
    /// <inheritdoc/>
    public override BoolPrimitive Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        try
        {
            return JsonInternalConverters.BooleanConverter.Read(ref reader, typeToConvert, options);
        }
        catch (InvalidPrimitiveValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void Write(Utf8JsonWriter writer, BoolPrimitive value, JsonSerializerOptions options)
    {
        JsonInternalConverters.BooleanConverter.Write(writer, (bool)value, options);
    }

    /// <inheritdoc/>
    public override BoolPrimitive ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        try
        {
            return JsonInternalConverters.BooleanConverter.ReadAsPropertyName(ref reader, typeToConvert, options);
        }
        catch (InvalidPrimitiveValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void WriteAsPropertyName(Utf8JsonWriter writer, BoolPrimitive value, JsonSerializerOptions options)
    {
        JsonInternalConverters.BooleanConverter.WriteAsPropertyName(writer, (bool)value, options);
    }
}
