//HintName: DateOnlyPrimitiveJsonConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Headless.Permissions;
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;
using System.Text.Json.Serialization.Metadata;
using Headless.Generator.Primitives;

namespace Headless.Primitives.Converters;

/// <summary>JsonConverter for <see cref = "DateOnlyPrimitive"/></summary>
public sealed class DateOnlyPrimitiveJsonConverter : JsonConverter<DateOnlyPrimitive>
{
    /// <inheritdoc/>
    public override DateOnlyPrimitive Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        try
        {
            return JsonInternalConverters.DateOnlyConverter.Read(ref reader, typeToConvert, options);
        }
        catch (InvalidPrimitiveValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void Write(Utf8JsonWriter writer, DateOnlyPrimitive value, JsonSerializerOptions options)
    {
        JsonInternalConverters.DateOnlyConverter.Write(writer, (DateOnly)value, options);
    }

    /// <inheritdoc/>
    public override DateOnlyPrimitive ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        try
        {
            return JsonInternalConverters.DateOnlyConverter.ReadAsPropertyName(ref reader, typeToConvert, options);
        }
        catch (InvalidPrimitiveValueException ex)
        {
            throw new JsonException(ex.Message);
        }
    }

    /// <inheritdoc/>
    public override void WriteAsPropertyName(Utf8JsonWriter writer, DateOnlyPrimitive value, JsonSerializerOptions options)
    {
        JsonInternalConverters.DateOnlyConverter.WriteAsPropertyName(writer, (DateOnly)value, options);
    }
}
