FROM mcr.microsoft.com/dotnet/aspnet:10.0@sha256:1fa23fc4872d95fd71c2833ebe65d7e84a43b2d51a31d119516852f13d9505a7
WORKDIR /app
COPY . ./
ENTRYPOINT ["dotnet", "Headless.Messaging.Dashboard.Jwt.Demo.dll"]
