// Copyright (c) Mahmoud Shaheen. All rights reserved.

using Headless.Hosting.Initialization;
using Headless.Hosting.Initialization.Schema;
using Headless.Sql.PostgreSql;

namespace Headless.AuditLog.PostgreSql;

/// <summary>
/// The AuditLog feature's schema contribution for PostgreSQL: the audit log table and its read indexes, as two
/// idempotent steps the Headless schema runner applies.
/// </summary>
internal static class PostgreSqlAuditLogSchemaContribution
{
    public const string TableStepVersion = "1";
    public const string IndexesStepVersion = "2";

    public static SchemaContribution Create(
        PostgreSqlAuditLogOptions providerOptions,
        AuditLogStorageOptions storageOptions
    )
    {
        var tableName = PostgreSqlAuditLogSchema.TableName(storageOptions);
        var table = PostgreSqlAuditLogSchema.Qualified(storageOptions);
        var primaryKey = HeadlessStorageNaming.PrimaryKeyName(StorageNamingStyle.SnakeCase, tableName);
        var jsonColumnType = (storageOptions.JsonColumnType ?? AuditLogJsonColumnType.Jsonb).ToSqlFragment();
        var createdAtColumnType = string.IsNullOrWhiteSpace(storageOptions.CreatedAtColumnType)
            ? "timestamp with time zone"
            : storageOptions.CreatedAtColumnType;

        var tableSql = $"""
            CREATE TABLE IF NOT EXISTS {table} (
                "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "created_at" {createdAtColumnType} NOT NULL,
                "user_id" character varying({AuditLogFieldLimits.UserId}),
                "account_id" character varying({AuditLogFieldLimits.AccountId}),
                "tenant_id" character varying({AuditLogFieldLimits.TenantId}),
                "ip_address" character varying({AuditLogFieldLimits.IpAddress}),
                "user_agent" character varying({AuditLogFieldLimits.UserAgent}),
                "correlation_id" character varying({AuditLogFieldLimits.CorrelationId}),
                "action" character varying({AuditLogFieldLimits.Action}) NOT NULL,
                "change_type" integer,
                "entity_type" character varying({AuditLogFieldLimits.EntityType}),
                "entity_id" character varying({AuditLogFieldLimits.EntityId}),
                "old_values" {jsonColumnType},
                "new_values" {jsonColumnType},
                "changed_fields" {jsonColumnType},
                "success" boolean NOT NULL,
                "error_code" character varying({AuditLogFieldLimits.ErrorCode}),
                CONSTRAINT "{primaryKey}" PRIMARY KEY ("created_at", "id")
            );
            """;

        // Each index ends in (created_at, id), the keyset order of read paging, so a filtered page seeks straight
        // to its continuation position instead of scanning.
        var indexesSql = $"""
            CREATE INDEX IF NOT EXISTS "{_IndexName(
                tableName,
                AuditLogStorageNames.TenantTime
            )}" ON {table} ("tenant_id", "created_at", "id");
            CREATE INDEX IF NOT EXISTS "{_IndexName(
                tableName,
                AuditLogStorageNames.TenantActionTime
            )}" ON {table} ("tenant_id", "action", "created_at", "id");
            CREATE INDEX IF NOT EXISTS "{_IndexName(
                tableName,
                AuditLogStorageNames.TenantEntityTime
            )}" ON {table} ("tenant_id", "entity_type", "entity_id", "created_at", "id");
            CREATE INDEX IF NOT EXISTS "{_IndexName(
                tableName,
                AuditLogStorageNames.TenantActorTime
            )}" ON {table} ("tenant_id", "user_id", "created_at", "id");
            CREATE INDEX IF NOT EXISTS "{_IndexName(
                tableName,
                AuditLogStorageNames.TenantAccountTime
            )}" ON {table} ("tenant_id", "account_id", "created_at", "id");
            CREATE INDEX IF NOT EXISTS "{_IndexName(
                tableName,
                AuditLogStorageNames.Correlation
            )}" ON {table} ("correlation_id", "created_at", "id");
            """;

        return new SchemaContribution(
            feature: SchemaContribution.FeatureId(
                "AuditLog",
                (
                    tableName,
                    HeadlessStorageNaming.Apply(StorageNamingStyle.SnakeCase, AuditLogStorageNames.DefaultTableName)
                )
            ),
            dialect: PostgreSqlSchemaDialect.Instance,
            createConnection: providerOptions.CreateConnection,
            schema: storageOptions.Schema,
            steps:
            [
                new SchemaStep(TableStepVersion, "Create the audit log table.", tableSql),
                new SchemaStep(IndexesStepVersion, "Create the audit log read indexes.", indexesSql),
            ],
            applyOnStartup: storageOptions.InitializeOnStartup
        );
    }

    private static string _IndexName(string tableName, string[] parts)
    {
        return HeadlessStorageNaming.IndexName(StorageNamingStyle.SnakeCase, tableName, parts);
    }
}
