// Copyright (c) Mahmoud Shaheen. All rights reserved.

using Headless.AuditLog;
using Headless.Hosting.Initialization;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using Npgsql;

namespace Headless.AuditLog.PostgreSql;

internal sealed class PostgreSqlAuditLogStorageInitializer(
    IOptions<PostgreSqlAuditLogOptions> providerOptions,
    IOptions<AuditLogStorageOptions> storageOptions
) : IHostedLifecycleService, IInitializer
{
    private TaskCompletionSource _completion = new(TaskCreationOptions.RunContinuationsAsynchronously);

    public bool IsInitialized { get; private set; }

    public async Task StartingAsync(CancellationToken cancellationToken)
    {
        // Recreate the completion source so retries (host re-starts) get a fresh promise.
        _completion = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

        try
        {
            await InitializeAsync(cancellationToken).ConfigureAwait(false);
            IsInitialized = true;
            _completion.TrySetResult();
        }
        catch (Exception ex)
        {
            _completion.TrySetException(ex);
            throw;
        }
    }

    public Task StartAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    public Task StartedAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    public Task StoppingAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    public Task StoppedAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    public async Task WaitForInitializationAsync(CancellationToken cancellationToken = default)
    {
        await _completion.Task.WaitAsync(cancellationToken).ConfigureAwait(false);
    }

    public async Task InitializeAsync(CancellationToken cancellationToken = default)
    {
        var options = storageOptions.Value;
        var sql = _CreateScript(options);
        await using var connection = providerOptions.Value.CreateConnection();
        await connection.OpenAsync(cancellationToken).ConfigureAwait(false);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);

        try
        {
            await using var command = new NpgsqlCommand(sql, connection, transaction)
            {
                CommandTimeout = (int)providerOptions.Value.CommandTimeout.TotalSeconds,
            };
            await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
            await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
        }
        catch (PostgresException ex) when (ex.SqlState is "42P06" or "42P07" or "42710")
        {
            await transaction.RollbackAsync(CancellationToken.None).ConfigureAwait(false);
        }
    }

    internal static string Qualified(AuditLogStorageOptions options) =>
        $@"""{options.Schema}"".""{options.TableName}""";

    private static string _CreateScript(AuditLogStorageOptions options)
    {
        var table = Qualified(options);
        var createSchema = $"""CREATE SCHEMA IF NOT EXISTS "{options.Schema}";""";
        var jsonColumnType = (options.JsonColumnType ?? AuditLogJsonColumnType.Jsonb).ToSqlFragment();

        return $"""
            {createSchema}

            CREATE TABLE IF NOT EXISTS {table} (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UserId" character varying(128),
                "AccountId" character varying(128),
                "TenantId" character varying(128),
                "IpAddress" character varying(45),
                "UserAgent" character varying(512),
                "CorrelationId" character varying(128),
                "Action" character varying(256) NOT NULL,
                "ChangeType" integer,
                "EntityType" character varying(512),
                "EntityId" character varying(256),
                "OldValues" {jsonColumnType},
                "NewValues" {jsonColumnType},
                "ChangedFields" {jsonColumnType},
                "Success" boolean NOT NULL,
                "ErrorCode" character varying(256),
                CONSTRAINT "PK_{options.TableName}" PRIMARY KEY ("CreatedAt", "Id")
            );

            CREATE INDEX IF NOT EXISTS "ix_audit_log_tenant_time" ON {table} ("TenantId", "CreatedAt");
            CREATE INDEX IF NOT EXISTS "ix_audit_log_tenant_action_time" ON {table} ("TenantId", "Action", "CreatedAt");
            CREATE INDEX IF NOT EXISTS "ix_audit_log_tenant_entity_time" ON {table} ("TenantId", "EntityType", "EntityId", "CreatedAt");
            CREATE INDEX IF NOT EXISTS "ix_audit_log_tenant_actor_time" ON {table} ("TenantId", "UserId", "CreatedAt");
            CREATE INDEX IF NOT EXISTS "ix_audit_log_correlation" ON {table} ("CorrelationId");
            """;
    }
}
