// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tests.Fixture;

#nullable disable

namespace Tests.Fixture.Migrations;

[DbContext(typeof(TenantMigrationDbContext))]
partial class TenantMigrationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("app")
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Tests.Fixture.MigratedNote", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Notes", "app");
            });

        modelBuilder.Entity("Tests.Fixture.MigratedRow", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("TenantId")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.HasKey("Id");

                b.HasIndex("Name");

                b.ToTable("Rows", "app");

                b
                    .HasAnnotation("Headless:Tenant:IsOwned", true)
                    .HasAnnotation("Headless:Tenant:PropertyName", "TenantId");

                b.HasData(
                    new
                    {
                        Id = new Guid("0198f6a4-0000-7000-8000-000000000001"),
                        Name = "seeded",
                        TenantId = "seed"
                    });
            });
#pragma warning restore 612, 618
    }
}
