<Project Sdk="Headless.NET.Sdk.Test">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tests</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Headless.UnitOfWork.Abstractions\Headless.UnitOfWork.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Headless.UnitOfWork\Headless.UnitOfWork.csproj" />
    <ProjectReference Include="..\..\src\Headless.UnitOfWork.SqlServer\Headless.UnitOfWork.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Headless.Testing.Testcontainers\Headless.Testing.Testcontainers.csproj" />
    <ProjectReference Include="..\Headless.UnitOfWork.Tests.Harness\Headless.UnitOfWork.Tests.Harness.csproj" />
  </ItemGroup>
</Project>
