<Project Sdk="Headless.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Description>Roslyn source generator for Headless primitive types and converters.</Description>
    <PackageTags>headless;generator;primitives;source-generator;dotnet</PackageTags>
  </PropertyGroup>
  <Import Project="..\Headless.SourceGenerators.Shared\Headless.SourceGenerators.Shared.props" />
  <ItemGroup>
    <CompilerVisibleProperty Include="PrimitiveJsonConverters" />
    <CompilerVisibleProperty Include="PrimitiveXmlConverters" />
    <CompilerVisibleProperty Include="PrimitiveTypeConverters" />
    <CompilerVisibleProperty Include="PrimitiveSwashbuckleSwaggerConverters" />
    <CompilerVisibleProperty Include="PrimitiveNswagSwaggerConverters" />
    <CompilerVisibleProperty Include="PrimitiveEntityFrameworkValueConverters" />
    <CompilerVisibleProperty Include="PrimitiveDapperConverters" />
  </ItemGroup>
  <ItemGroup>
    <None Include="buildTransitive\*.props" Pack="true" PackagePath="buildTransitive\" />
  </ItemGroup>
</Project>
