// Copyright (c) Mahmoud Shaheen. All rights reserved.

using System.Reflection;
using Headless.Generator.Primitives;
using Headless.Reflection;
using NJsonSchema.Generation;

namespace Headless.Api.Extensions;

/// <summary>
/// Extension methods on <c>JsonSchemaGeneratorSettings</c> for registering NJsonSchema type mappers
/// generated by the Headless primitives source generator.
/// </summary>
/// <remarks>
/// Each Headless primitives assembly that carries a <c>[PrimitiveAssembly]</c> attribute emits a static
/// class named <c>AddSwashbuckleSwaggerPrimitivesMappingsExtensions</c> with a method
/// <c>AddSwaggerPrimitiveMappings(JsonSchemaGeneratorSettings)</c>. The methods on this class discover
/// and invoke those generated methods via reflection so callers do not need to reference each primitives
/// assembly individually.
/// </remarks>
[PublicAPI]
public static class NswagSwaggerGenOptionsExtensions
{
    private const string _TypeName = "AddSwashbuckleSwaggerPrimitivesMappingsExtensions";
    private const string _MethodName = "AddSwaggerPrimitiveMappings";

    /// <summary>
    /// Registers NJsonSchema type mappers for all Headless primitive types found in the specified assemblies.
    /// </summary>
    /// <param name="options">The <c>JsonSchemaGeneratorSettings</c> to add the mappers to.</param>
    /// <param name="assemblies">
    /// One or more assemblies to scan for the generated primitive mapper extension class.
    /// </param>
    public static void AddPrimitivesSwaggerMappings(
        this JsonSchemaGeneratorSettings options,
        params Assembly[] assemblies
    )
    {
        assemblies.InvokeAllStaticMethods(_TypeName, _MethodName, parameters: options);
    }

    /// <summary>
    /// Registers NJsonSchema type mappers for all Headless primitive types found in every currently-loaded
    /// assembly that carries a <c>[PrimitiveAssembly]</c> attribute.
    /// </summary>
    /// <param name="options">The <c>JsonSchemaGeneratorSettings</c> to add the mappers to.</param>
    public static void AddAllPrimitivesSwaggerMappings(this JsonSchemaGeneratorSettings options)
    {
        var assemblies = AssemblyHelper.GetCurrentAssemblies(
            acceptPredicate: assembly => Attribute.IsDefined(assembly, typeof(PrimitiveAssemblyAttribute)),
            excludePredicate: AssemblyHelper.IsSystemAssemblyName
        );

        assemblies.InvokeAllStaticMethods(_TypeName, _MethodName, parameters: options);
    }

    /// <summary>
    /// Registers NJsonSchema type mappers for all Headless primitive types found in the specified assembly
    /// sequence.
    /// </summary>
    /// <param name="options">The <c>JsonSchemaGeneratorSettings</c> to add the mappers to.</param>
    /// <param name="assemblies">The assemblies to scan for generated primitive mapper extension classes.</param>
    public static void AddAllPrimitivesSwaggerMappings(
        this JsonSchemaGeneratorSettings options,
        IEnumerable<Assembly> assemblies
    )
    {
        assemblies.InvokeAllStaticMethods(_TypeName, _MethodName, parameters: options);
    }
}
