using System.Diagnostics.CodeAnalysis;
using Framework.Api.Mvc.Filters;
using Framework.Kernel.Checks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Options;

namespace Framework.Api.Mvc.Middlewares;

/// <summary>
/// To improve Search Engine Optimization SEO, there should only be a single URL for each resource. Case
/// differences and/or URL's with/without trailing slashes are treated as different URL's by search engines. This
/// rewrite rule redirects all non-canonical URL's based on the settings specified to their canonical equivalent.
/// Note: Non-canonical URL's are not generated by this site template, it is usually external sites which are
/// linking to your site but have changed the URL case or added/removed trailing slashes.
/// (See Google's comments at http://googlewebmastercentral.blogspot.co.uk/2010/04/to-slash-or-not-to-slash.html
/// and Bing's at http://blogs.bing.com/webmaster/2012/01/26/moving-content-think-301-not-relcanonical).
/// </summary>
public sealed class RedirectToCanonicalUrlRule : IRule
{
    private const char _SlashCharacter = '/';

    public RedirectToCanonicalUrlRule(IOptions<RouteOptions> options)
    {
        Argument.IsNotNull(options);
        AppendTrailingSlash = options.Value.AppendTrailingSlash;
        LowercaseUrls = options.Value.LowercaseUrls;
    }

    public RedirectToCanonicalUrlRule(bool appendTrailingSlash, bool lowercaseUrls)
    {
        AppendTrailingSlash = appendTrailingSlash;
        LowercaseUrls = lowercaseUrls;
    }

    /// <summary>
    /// Gets a value indicating whether to append trailing slashes.
    /// </summary>
    /// <value>
    /// <see langword="true"/> if appending trailing slashes; otherwise, strip trailing slashes.
    /// </value>
    public bool AppendTrailingSlash { get; }

    /// <summary>
    /// Gets a value indicating whether to lower-case all URL's.
    /// </summary>
    /// <value>
    /// <see langword="true"/> if lower-casing URL's; otherwise, <see langword="false"/>.
    /// </value>
    public bool LowercaseUrls { get; }

    public void ApplyRule(RewriteContext context)
    {
        ArgumentNullException.ThrowIfNull(context);

        if (HttpMethods.IsGet(context.HttpContext.Request.Method))
        {
            if (!_TryGetCanonicalUrl(context, out var canonicalUrl))
            {
                _HandleNonCanonicalRequest(context, canonicalUrl);
            }
        }
    }

    /// <summary>
    /// Determines whether the specified URl is canonical and if it is not, outputs the canonical URL.
    /// </summary>
    /// <param name="context">The <see cref="RewriteContext" />.</param>
    /// <param name="canonicalUrl">The canonical URL.</param>
    /// <returns><see langword="true"/> if the URL is canonical, otherwise <see langword="false"/>.</returns>
    private bool _TryGetCanonicalUrl(RewriteContext context, [NotNullWhen(false)] out Uri? canonicalUrl)
    {
        ArgumentNullException.ThrowIfNull(context);

        var isCanonical = true;

        var request = context.HttpContext.Request;
        var hasPath = request.Path.HasValue && request.Path.Value.Length > 1;

        // If we are not dealing with the home page. Note, the home page is a special case and it doesn't matter
        // if there is a trailing slash or not. Both will be treated as the same by search engines.
        if (hasPath)
        {
            var hasTrailingSlash = request.Path.Value![^1] == _SlashCharacter;

            if (AppendTrailingSlash)
            {
                // Append a trailing slash to the end of the URL.
                if (!hasTrailingSlash && !_HasAttribute<NoTrailingSlashAttribute>(context))
                {
                    request.Path = new PathString(request.Path.Value + _SlashCharacter);
                    isCanonical = false;
                }
            }
            else
            {
                // Trim a trailing slash from the end of the URL.
                if (hasTrailingSlash)
                {
                    request.Path = new PathString(request.Path.Value.TrimEnd(_SlashCharacter));
                    isCanonical = false;
                }
            }
        }

        if (hasPath || request.QueryString.HasValue)
        {
            if (LowercaseUrls && !_HasAttribute<NoTrailingSlashAttribute>(context))
            {
                foreach (var character in request.Path.Value!)
                {
                    if (char.IsUpper(character))
                    {
#pragma warning disable CA1308 // Normalize strings to uppercase
                        request.Path = new PathString(request.Path.Value.ToLowerInvariant());
#pragma warning restore CA1308 // Normalize strings to uppercase
                        isCanonical = false;

                        break;
                    }
                }

                if (request.QueryString.HasValue && !_HasAttribute<NoLowercaseQueryStringAttribute>(context))
                {
                    foreach (var character in request.QueryString.Value!)
                    {
                        if (char.IsUpper(character))
                        {
#pragma warning disable CA1308 // Normalize strings to uppercase
                            request.QueryString = new QueryString(request.QueryString.Value.ToLowerInvariant());
#pragma warning restore CA1308 // Normalize strings to uppercase
                            isCanonical = false;

                            break;
                        }
                    }
                }
            }
        }

        if (isCanonical)
        {
            canonicalUrl = null;
        }
        else
        {
            canonicalUrl = new Uri(request.GetEncodedUrl(), UriKind.Absolute);
        }

        return isCanonical;
    }

    /// <summary>
    /// Handles HTTP requests for URL's that are not canonical. Performs a 301 Permanent Redirect to the canonical URL.
    /// </summary>
    /// <param name="context">The <see cref="RewriteContext" />.</param>
    /// <param name="canonicalUrl">The canonical URL.</param>
    private static void _HandleNonCanonicalRequest(RewriteContext context, Uri canonicalUrl)
    {
        Argument.IsNotNull(context);
        Argument.IsNotNull(canonicalUrl);

        var response = context.HttpContext.Response;
        response.StatusCode = StatusCodes.Status301MovedPermanently;
        context.Result = RuleResult.EndResponse;
        response.Headers.Location = canonicalUrl.ToString();
    }

    /// <summary>
    /// Determines whether the specified action or its controller has the attribute with the specified type
    /// <typeparamref name="T"/>.
    /// </summary>
    /// <typeparam name="T">The type of the attribute.</typeparam>
    /// <param name="context">The <see cref="RewriteContext" />.</param>
    /// <returns><see langword="true"/> if a <typeparamref name="T"/> attribute is specified, otherwise <see langword="false"/>.</returns>
    private static bool _HasAttribute<T>(RewriteContext context)
        where T : class
    {
        Argument.IsNotNull(context);

        var endpoint = context.HttpContext.GetEndpoint();

        return endpoint?.Metadata.GetMetadata<T>() is not null;
    }
}
