//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.FluentValidation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FluentValidatorErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FluentValidatorErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.FluentValidation.Resources.FluentValidatorErrors", typeof(FluentValidatorErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of &apos;{PropertyName}&apos; must be less than {MaxLength} MB. You uploaded {TotalLength} MB..
        /// </summary>
        internal static string file_greater_than_or_equal_to {
            get {
                return ResourceManager.GetString("file:greater_than_or_equal_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of &apos;{PropertyName}&apos; must be at least {MinLength} MB. You uploaded {TotalLength} MB..
        /// </summary>
        internal static string file_less_than_or_equal_to {
            get {
                return ResourceManager.GetString("file:less_than_or_equal_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must not be empty..
        /// </summary>
        internal static string file_not_empty {
            get {
                return ResourceManager.GetString("file:not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type is not allowed..
        /// </summary>
        internal static string file_unexpected_signature {
            get {
                return ResourceManager.GetString("file:unexpected_signature", resourceCulture);
            }
        }
    }
}
