//HintName: SetupAcme.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Headless.Generator.ProviderSetup'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

#pragma warning disable IDE0130 // registration surface lives in the family root namespace

using System;
using Headless.Checks;
using Headless.Http.Effects;
using Headless.Sms;
using Acme.Sms;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Headless.Sms;

/// <summary>Generated registration surface for UseAcme. Extension members on <see cref="HeadlessSmsSetupBuilder"/>.</summary>
public static class SetupAcme
{
    internal const string HttpClientName = "Headless:AcmeSms";

    extension(HeadlessSmsSetupBuilder setup)
    {
        /// <summary>Selects Acme, binding and validating <see cref="Acme.Sms.AcmeSmsOptions"/> from configuration.</summary>
        /// <remarks>The HTTP resilience pipeline is derived from the declared <c>OutboundEffect.Unsafe</c> effect; pass <paramref name="configureResilience"/> to override it explicitly.</remarks>
        /// <param name="config">Configuration section containing <see cref="Acme.Sms.AcmeSmsOptions"/> values.</param>
        /// <param name="configureClient">Optional delegate to further configure the underlying <see cref="global::System.Net.Http.HttpClient"/>.</param>
        /// <param name="configureResilience">Optional delegate applied after the derived resilience defaults.</param>
        /// <returns>The same builder, for chaining.</returns>
        /// <exception cref="global::System.ArgumentNullException"><paramref name="config"/> is <see langword="null"/>.</exception>
        [global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Binding options from IConfiguration uses reflection. Use the Action<TOptions> overload in trimmed or native AOT apps.")]
        [global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Binding options from IConfiguration may need runtime code generation. Use the Action<TOptions> overload in native AOT apps.")]
        public HeadlessSmsSetupBuilder UseAcme(
            IConfiguration config,
            Action<global::System.Net.Http.HttpClient>? configureClient = null,
            Action<global::Microsoft.Extensions.Http.Resilience.HttpStandardResilienceOptions>? configureResilience = null
        )
        {
            Argument.IsNotNull(config);

            setup.RegisterDefaultProvider(services =>
                SetupAcme.AddAcmeSmsCore(
                    services,
                    name: null,
                    (s, n) => s.Configure<global::Acme.Sms.AcmeSmsOptions, global::Acme.Sms.AcmeSmsOptionsValidator>(config, n),
                    configureClient,
                    configureResilience
                )
            );

            return setup;
        }

        /// <summary>Selects Acme, configuring <see cref="Acme.Sms.AcmeSmsOptions"/> via a delegate.</summary>
        /// <remarks>The HTTP resilience pipeline is derived from the declared <c>OutboundEffect.Unsafe</c> effect; pass <paramref name="configureResilience"/> to override it explicitly.</remarks>
        /// <param name="setupAction">Delegate that populates the options.</param>
        /// <param name="configureClient">Optional delegate to further configure the underlying <see cref="global::System.Net.Http.HttpClient"/>.</param>
        /// <param name="configureResilience">Optional delegate applied after the derived resilience defaults.</param>
        /// <returns>The same builder, for chaining.</returns>
        /// <exception cref="global::System.ArgumentNullException"><paramref name="setupAction"/> is <see langword="null"/>.</exception>
        public HeadlessSmsSetupBuilder UseAcme(
            Action<global::Acme.Sms.AcmeSmsOptions> setupAction,
            Action<global::System.Net.Http.HttpClient>? configureClient = null,
            Action<global::Microsoft.Extensions.Http.Resilience.HttpStandardResilienceOptions>? configureResilience = null
        )
        {
            Argument.IsNotNull(setupAction);

            setup.RegisterDefaultProvider(services =>
                SetupAcme.AddAcmeSmsCore(
                    services,
                    name: null,
                    (s, n) => s.Configure<global::Acme.Sms.AcmeSmsOptions, global::Acme.Sms.AcmeSmsOptionsValidator>(setupAction, n),
                    configureClient,
                    configureResilience
                )
            );

            return setup;
        }

        /// <summary>Selects Acme, configuring <see cref="Acme.Sms.AcmeSmsOptions"/> with access to the service provider.</summary>
        /// <remarks>The HTTP resilience pipeline is derived from the declared <c>OutboundEffect.Unsafe</c> effect; pass <paramref name="configureResilience"/> to override it explicitly.</remarks>
        /// <param name="setupAction">Delegate that populates the options.</param>
        /// <param name="configureClient">Optional delegate to further configure the underlying <see cref="global::System.Net.Http.HttpClient"/>.</param>
        /// <param name="configureResilience">Optional delegate applied after the derived resilience defaults.</param>
        /// <returns>The same builder, for chaining.</returns>
        /// <exception cref="global::System.ArgumentNullException"><paramref name="setupAction"/> is <see langword="null"/>.</exception>
        public HeadlessSmsSetupBuilder UseAcme(
            Action<global::Acme.Sms.AcmeSmsOptions, IServiceProvider> setupAction,
            Action<global::System.Net.Http.HttpClient>? configureClient = null,
            Action<global::Microsoft.Extensions.Http.Resilience.HttpStandardResilienceOptions>? configureResilience = null
        )
        {
            Argument.IsNotNull(setupAction);

            setup.RegisterDefaultProvider(services =>
                SetupAcme.AddAcmeSmsCore(
                    services,
                    name: null,
                    (s, n) => s.Configure<global::Acme.Sms.AcmeSmsOptions, global::Acme.Sms.AcmeSmsOptionsValidator>(setupAction, n),
                    configureClient,
                    configureResilience
                )
            );

            return setup;
        }
    }

    /// <summary>Registers the provider sender; the resilience pipeline is derived from the declared effect.</summary>
    internal static void AddAcmeSmsCore(
        IServiceCollection services,
        string? name,
        Action<IServiceCollection, string?> configureOptions,
        Action<global::System.Net.Http.HttpClient>? configureClient,
        Action<global::Microsoft.Extensions.Http.Resilience.HttpStandardResilienceOptions>? configureResilience
    )
    {
        configureOptions(services, name);

        var httpClientName = GetHttpClientName(name);

        var httpClientBuilder = configureClient is null
            ? services.AddHttpClient(httpClientName)
            : services.AddHttpClient(httpClientName, configureClient);

        // The resilience pipeline is derived from the options class's [OutboundEffect] declaration;
        // the derivation removes any host-wide default handler first, so the declaration always wins.
        httpClientBuilder.AddEffectResilienceHandler(
            global::Headless.Http.Effects.OutboundEffect.Unsafe,
            idempotencyHeader: null,
            configureResilience: configureResilience
        );

        if (name is null)
        {
            services.AddSingleton<ISmsSender>(static sp => _CreateSender(sp, HttpClientName, optionsName: null));
            services.AddSingleton<IBulkSmsSender>(static sp => (IBulkSmsSender)sp.GetRequiredService<ISmsSender>());

            return;
        }

        services.AddKeyedSingleton<ISmsSender>(name, (sp, _) => _CreateSender(sp, httpClientName, name));
        services.AddKeyedSingleton<IBulkSmsSender>(
            name,
            (sp, _) => (IBulkSmsSender)sp.GetRequiredKeyedService<ISmsSender>(name)
        );
    }

    /// <summary>Each named instance gets its own client, and so its own resilience pipeline.</summary>
    internal static string GetHttpClientName(string? name)
    {
        return name is null ? HttpClientName : $"{HttpClientName}:{name}";
    }

    private static global::Acme.Sms.AcmeSmsSender _CreateSender(
        IServiceProvider sp,
        string httpClientName,
        string? optionsName
    )
    {
        return new global::Acme.Sms.AcmeSmsSender(sp.GetRequiredService<global::System.Net.Http.IHttpClientFactory>(), httpClientName, sp.GetRequiredService<IOptionsMonitor<global::Acme.Sms.AcmeSmsOptions>>(), optionsName, sp.GetRequiredService<ILogger<global::Acme.Sms.AcmeSmsSender>>());
    }
}

/// <summary>Generated registration surface for named UseAcme instances. Extension members on <see cref="HeadlessSmsInstanceBuilder"/>.</summary>
public static class SetupAcmeNamed
{
    extension(HeadlessSmsInstanceBuilder instance)
    {
        /// <summary>Uses Acme for this named instance, binding and validating <see cref="Acme.Sms.AcmeSmsOptions"/> from configuration.</summary>
        /// <remarks>The HTTP resilience pipeline is derived from the declared <c>OutboundEffect.Unsafe</c> effect; pass <paramref name="configureResilience"/> to override it explicitly.</remarks>
        /// <param name="config">Configuration section containing <see cref="Acme.Sms.AcmeSmsOptions"/> values.</param>
        /// <param name="configureClient">Optional delegate to further configure the underlying <see cref="global::System.Net.Http.HttpClient"/>.</param>
        /// <param name="configureResilience">Optional delegate applied after the derived resilience defaults.</param>
        /// <returns>The same builder, for chaining.</returns>
        /// <exception cref="global::System.ArgumentNullException"><paramref name="config"/> is <see langword="null"/>.</exception>
        [global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("Binding options from IConfiguration uses reflection. Use the Action<TOptions> overload in trimmed or native AOT apps.")]
        [global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode("Binding options from IConfiguration may need runtime code generation. Use the Action<TOptions> overload in native AOT apps.")]
        public HeadlessSmsInstanceBuilder UseAcme(
            IConfiguration config,
            Action<global::System.Net.Http.HttpClient>? configureClient = null,
            Action<global::Microsoft.Extensions.Http.Resilience.HttpStandardResilienceOptions>? configureResilience = null
        )
        {
            Argument.IsNotNull(config);

            var name = instance.Name;

            instance.RegisterProvider(services =>
                SetupAcme.AddAcmeSmsCore(
                    services,
                    name,
                    (s, n) => s.Configure<global::Acme.Sms.AcmeSmsOptions, global::Acme.Sms.AcmeSmsOptionsValidator>(config, n),
                    configureClient,
                    configureResilience
                )
            );

            return instance;
        }

        /// <summary>Uses Acme for this named instance, configuring <see cref="Acme.Sms.AcmeSmsOptions"/> via a delegate.</summary>
        /// <remarks>The HTTP resilience pipeline is derived from the declared <c>OutboundEffect.Unsafe</c> effect; pass <paramref name="configureResilience"/> to override it explicitly.</remarks>
        /// <param name="setupAction">Delegate that populates the options.</param>
        /// <param name="configureClient">Optional delegate to further configure the underlying <see cref="global::System.Net.Http.HttpClient"/>.</param>
        /// <param name="configureResilience">Optional delegate applied after the derived resilience defaults.</param>
        /// <returns>The same builder, for chaining.</returns>
        /// <exception cref="global::System.ArgumentNullException"><paramref name="setupAction"/> is <see langword="null"/>.</exception>
        public HeadlessSmsInstanceBuilder UseAcme(
            Action<global::Acme.Sms.AcmeSmsOptions> setupAction,
            Action<global::System.Net.Http.HttpClient>? configureClient = null,
            Action<global::Microsoft.Extensions.Http.Resilience.HttpStandardResilienceOptions>? configureResilience = null
        )
        {
            Argument.IsNotNull(setupAction);

            var name = instance.Name;

            instance.RegisterProvider(services =>
                SetupAcme.AddAcmeSmsCore(
                    services,
                    name,
                    (s, n) => s.Configure<global::Acme.Sms.AcmeSmsOptions, global::Acme.Sms.AcmeSmsOptionsValidator>(setupAction, n),
                    configureClient,
                    configureResilience
                )
            );

            return instance;
        }

        /// <summary>Uses Acme for this named instance, configuring <see cref="Acme.Sms.AcmeSmsOptions"/> with access to the service provider.</summary>
        /// <remarks>The HTTP resilience pipeline is derived from the declared <c>OutboundEffect.Unsafe</c> effect; pass <paramref name="configureResilience"/> to override it explicitly.</remarks>
        /// <param name="setupAction">Delegate that populates the options.</param>
        /// <param name="configureClient">Optional delegate to further configure the underlying <see cref="global::System.Net.Http.HttpClient"/>.</param>
        /// <param name="configureResilience">Optional delegate applied after the derived resilience defaults.</param>
        /// <returns>The same builder, for chaining.</returns>
        /// <exception cref="global::System.ArgumentNullException"><paramref name="setupAction"/> is <see langword="null"/>.</exception>
        public HeadlessSmsInstanceBuilder UseAcme(
            Action<global::Acme.Sms.AcmeSmsOptions, IServiceProvider> setupAction,
            Action<global::System.Net.Http.HttpClient>? configureClient = null,
            Action<global::Microsoft.Extensions.Http.Resilience.HttpStandardResilienceOptions>? configureResilience = null
        )
        {
            Argument.IsNotNull(setupAction);

            var name = instance.Name;

            instance.RegisterProvider(services =>
                SetupAcme.AddAcmeSmsCore(
                    services,
                    name,
                    (s, n) => s.Configure<global::Acme.Sms.AcmeSmsOptions, global::Acme.Sms.AcmeSmsOptionsValidator>(setupAction, n),
                    configureClient,
                    configureResilience
                )
            );

            return instance;
        }
    }
}
