//HintName: LongValueValueConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Framework.Primitives;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Framework.Generator.Primitives;

namespace Framework.Primitives.EntityFrameworkCore.Converters;

/// <summary>ValueConverter for <see cref = "LongValue"/></summary>
public sealed class LongValueValueConverter : ValueConverter<LongValue, ulong>
{
    public LongValueValueConverter() : base(v => v, v => v) { }

    public LongValueValueConverter(ConverterMappingHints? mappingHints = null) : base(v => v, v => v, mappingHints) { }
}
