//HintName: LongValueDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using Framework.Primitives;
using Framework.Generator.Primitives;

namespace Framework.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "LongValue"/></summary>
public sealed class LongValueDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<LongValue>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, LongValue value)
    {
        parameter.Value = value.GetUnderlyingPrimitiveType();
    }

    public override LongValue Parse(object value)
    {
        return value switch
        {
            ulong primitiveValue => new LongValue(primitiveValue),
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to LongValue"),
        };
    }
}
