//HintName: DateTimeOffsetPrimitiveDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using Framework.Primitives;
using Framework.Generator.Primitives;

namespace Framework.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "DateTimeOffsetPrimitive"/></summary>
public sealed class DateTimeOffsetPrimitiveDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<DateTimeOffsetPrimitive>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, DateTimeOffsetPrimitive value)
    {
        parameter.Value = value.GetUnderlyingPrimitiveType();
    }

    public override DateTimeOffsetPrimitive Parse(object value)
    {
        return value switch
        {
            DateTimeOffset dateTimeOffset => new DateTimeOffsetPrimitive(dateTimeOffset)
            string stringValue when !string.IsNullOrEmpty(stringValue) && DateTimeOffset.TryParseExact(stringValue, "o", global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.AssumeLocal, out var result) => new DateTimeOffsetPrimitive(result)
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to DateTimeOffsetPrimitive"),
        };
    }
}
