//HintName: GuidPrimitiveDapperTypeHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Framework.Primitives;
using System;
using System.ComponentModel;
using System.Globalization;
using Framework.Generator.Primitives;

namespace Framework.Primitives.Converters;

/// <summary>Dapper TypeHandler for <see cref = "GuidPrimitive"/></summary>
public sealed class GuidPrimitiveDapperTypeHandler : global::Dapper.SqlMapper.TypeHandler<GuidPrimitive>
{
    public override void SetValue(global::System.Data.IDbDataParameter parameter, GuidPrimitive value)
    {
        parameter.Value = value?.GetUnderlyingPrimitiveType();
    }

    public override GuidPrimitive Parse(object value)
    {
        return value switch
        {
            global::System.Guid guidValue => new GuidPrimitive(guidValue),
            string stringValue when !string.IsNullOrEmpty(stringValue) && global::System.Guid.TryParse(stringValue, out var result) => new GuidPrimitive(result),
            _ => throw new global::System.InvalidCastException($"Unable to cast object of type {value.GetType()} to GuidPrimitive"),
        };
    }
}
