//HintName: TimeOnlyPrimitiveValueConverter.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'Primitives Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Framework.Primitives;
using System;
using Framework.Generator.Primitives;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Framework.Primitives.Converters;

/// <summary>ValueConverter for <see cref = "TimeOnlyPrimitive"/></summary>
public sealed class TimeOnlyPrimitiveValueConverter : ValueConverter<TimeOnlyPrimitive, TimeOnly>
{
    public TimeOnlyPrimitiveValueConverter() : base(v => v, v => v) { }

    public TimeOnlyPrimitiveValueConverter(ConverterMappingHints? mappingHints = null) : base(v => v, v => v, mappingHints) { }
}
