// Copyright (c) Mahmoud Shaheen. All rights reserved.

namespace Headless.PushNotifications.Apns;

/// <summary>
/// Manages APNs broadcast channels for live activity updates.
/// </summary>
[PublicAPI]
public interface IApnsBroadcastChannelService
{
    /// <summary>Creates a broadcast channel.</summary>
    /// <param name="storagePolicy">The storage policy governing offline message retention.</param>
    /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
    /// <returns>The created broadcast channel instance.</returns>
    /// <exception cref="ApnsRequestException">APNs rejected the request.</exception>
    ValueTask<ApnsBroadcastChannel> CreateAsync(
        ApnsChannelStoragePolicy storagePolicy,
        CancellationToken cancellationToken = default
    );

    /// <summary>Retrieves configuration details for a broadcast channel.</summary>
    /// <param name="channelId">The broadcast channel identifier.</param>
    /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
    /// <returns>The broadcast channel configuration.</returns>
    /// <exception cref="ArgumentException"><paramref name="channelId"/> is empty or white space.</exception>
    /// <exception cref="ApnsRequestException">APNs rejected the request.</exception>
    ValueTask<ApnsBroadcastChannel> GetAsync(string channelId, CancellationToken cancellationToken = default);

    /// <summary>Lists active broadcast channel identifiers for the application.</summary>
    /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
    /// <returns>A read-only list of channel identifiers.</returns>
    /// <exception cref="ApnsRequestException">APNs rejected the request.</exception>
    ValueTask<IReadOnlyList<string>> ListAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes a broadcast channel.
    /// </summary>
    /// <param name="channelId">The channel identifier to delete.</param>
    /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
    /// <returns>A task representing the asynchronous delete operation.</returns>
    /// <exception cref="ArgumentException"><paramref name="channelId"/> is empty or white space.</exception>
    /// <exception cref="ApnsRequestException">APNs rejected the request.</exception>
    ValueTask DeleteAsync(string channelId, CancellationToken cancellationToken = default);
}

/// <summary>Specifies message storage policy for an APNs broadcast channel.</summary>
[PublicAPI]
public enum ApnsChannelStoragePolicy
{
    /// <summary>
    /// APNs delivers messages once and stores no offline messages.
    /// </summary>
    NoMessageStored = 0,

    /// <summary>
    /// APNs stores the most recent message for up to 8 hours for offline devices.
    /// </summary>
    MostRecentMessageStored = 1,
}

/// <summary>Represents an APNs broadcast channel.</summary>
/// <param name="Id">The channel identifier generated by APNs.</param>
/// <param name="StoragePolicy">The storage policy assigned during creation.</param>
[PublicAPI]
public sealed record ApnsBroadcastChannel(string Id, ApnsChannelStoragePolicy StoragePolicy);

/// <summary>Represents an exception thrown when APNs rejects a channel management request.</summary>
[PublicAPI]
public sealed class ApnsRequestException : Exception
{
    /// <summary>Initializes a new instance of the <see cref="ApnsRequestException"/> class.</summary>
    public ApnsRequestException() { }

    /// <summary>Initializes a new instance of the <see cref="ApnsRequestException"/> class with a message.</summary>
    /// <param name="message">The message describing the error.</param>
    public ApnsRequestException(string message)
        : base(message) { }

    /// <summary>Initializes a new instance of the <see cref="ApnsRequestException"/> class with a message and inner exception.</summary>
    /// <param name="message">The message describing the error.</param>
    /// <param name="innerException">The inner exception that caused this error.</param>
    public ApnsRequestException(string message, Exception innerException)
        : base(message, innerException) { }

    /// <summary>Initializes a new instance of the <see cref="ApnsRequestException"/> class with response details.</summary>
    /// <param name="message">The message describing the error.</param>
    /// <param name="statusCode">The HTTP status code returned by APNs.</param>
    /// <param name="reason">The error reason returned by APNs.</param>
    /// <param name="requestId">The request identifier from APNs headers.</param>
    public ApnsRequestException(string message, System.Net.HttpStatusCode statusCode, string? reason, string? requestId)
        : base(message)
    {
        StatusCode = statusCode;
        Reason = reason;
        RequestId = requestId;
    }

    /// <summary>Gets the HTTP status code returned by APNs.</summary>
    public System.Net.HttpStatusCode? StatusCode { get; }

    /// <summary>Gets the APNs error reason code, or <see langword="null"/> when not provided.</summary>
    public string? Reason { get; }

    /// <summary>Gets the <c>apns-request-id</c> header value from the rejected request.</summary>
    public string? RequestId { get; }
}
